galaxy_info:
  author: Jason Ernst
  role_name: github_cli
  description: Installs github cli (gh)
  company: ''
  license: GPLv3
  min_ansible_version: "2.20"
  platforms:
    - name: Ubuntu
      versions:
        - jammy  # 22.04 LTS
        - noble  # 24.04 LTS
  galaxy_tags:
    - github
    - cli
    - tools
