---
# we have to do this because there's no good way to make the change to /etc/environment.d
# take effect other than rebooting that I'm aware of
- name: Populate GH_TOKEN fact
  tags: gh
  ansible.builtin.shell: . /etc/environment.d/90-gh.conf && echo $GH_TOKEN
  register: github_cli_extension_gh_token_result
  changed_when: false

- name: Determine if the extension is present
  tags: gh
  # we must use shell because of the pipe operation
  ansible.builtin.shell: "gh extension list | grep {{ github_cli_extension_name }}"
  environment:
    GH_TOKEN: "{{ github_cli_extension_gh_token_result.stdout }}"
  register: github_cli_extension_extension_result
  ignore_errors: true
  changed_when: false

- name: Install the extension
  tags: gh
  ansible.builtin.command: "gh extension install {{ github_cli_extension_name }}"
  environment:
    GH_TOKEN: "{{ github_cli_extension_gh_token_result.stdout }}"
  when: github_cli_extension_extension_result.rc != 0
  register: github_cli_extension_extension_install_result
  changed_when: "'changed' in github_cli_extension_extension_install_result.stdout"
