---
- name: Get user home directory
  tags: gh
  ansible.builtin.getent:
    database: passwd
    key: "{{ github_cli_user | default(ansible_user) }}"

- name: Populate GH_TOKEN fact
  tags: gh
  become: true
  become_user: "{{ github_cli_user | default(ansible_user) }}"
  ansible.builtin.shell: . {{ getent_passwd[github_cli_user | default(ansible_user)][4] }}/.bashrc && echo $GH_TOKEN
  register: github_cli_extension_gh_token_result
  changed_when: false

- name: Determine if the extension is present
  tags: gh
  become: true
  become_user: "{{ github_cli_user | default(ansible_user) }}"
  # we must use shell because of the pipe operation
  ansible.builtin.shell: "gh extension list | grep {{ github_cli_extension_name }}"
  environment:
    GH_TOKEN: "{{ github_cli_extension_gh_token_result.stdout }}"
  register: github_cli_extension_extension_result
  ignore_errors: true
  changed_when: false

- name: Install the extension
  tags: gh
  become: true
  become_user: "{{ github_cli_user | default(ansible_user) }}"
  ansible.builtin.command: "gh extension install {{ github_cli_extension_name }}"
  environment:
    GH_TOKEN: "{{ github_cli_extension_gh_token_result.stdout }}"
  when: github_cli_extension_extension_result.rc != 0
  register: github_cli_extension_extension_install_result
  changed_when: "'changed' in github_cli_extension_extension_install_result.stdout"
