name: galaxy-ng-import
on:
  release:
    types: ["created"]

jobs:
  build:
    name: Galaxy Collection Importer
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install ansible-core
        run: pip install ansible-core

      - name: Build collection
        run: ansible-galaxy collection build

      - name: 'Release on galaxy'
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.galaxy_api_key }}
